# Generated by Django 5.2.3 on 2025-08-06 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mood_tracker', '0003_alter_moodentry_mood'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moodentry',
            name='mood',
            field=models.CharField(choices=[('very_happy', 'Very Happy'), ('happy', 'Happy'), ('excited', 'Excited'), ('calm', 'Calm'), ('content', 'Content'), ('neutral', 'Neutral'), ('tired', 'Tired'), ('sad', 'Sad'), ('angry', 'Angry'), ('anxious', 'Anxious'), ('stressed', 'Stressed')], max_length=20),
        ),
    ]
