# Generated by Django 5.2.3 on 2025-08-06 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mood_tracker', '0004_alter_moodentry_mood'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
